[package]
name = "my_todo_list"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='b50f46b6344af99dd208f35e780b7803ccbfb4a626389e139f2215afb70a1e56'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
